### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by kafagy95** [kafagy95/OrderData#30]
Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/kafagy/Documents/work/OrderData/Regression/OrderData.py", line 133, in test_addOrder
    addOrderObj.execute()
  File "/Users/kafagy/Documents/work/OrderData/Regression/addOrder.py", line 161, in execute
    self.parse(self.plugin.last_sent_raw, self.plugin.last_received_raw)
  File "/Users/kafagy/Documents/work/OrderData/Regression/addOrder.py", line 77, in parse
    soup = BeautifulSoup(resp_xml, 'xml')
  File "/Users/kafagy/.virtualenvs2.7/lib/python2.7/site-packages/bs4/__init__.py", line 192, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()

**Comment by kafagy95** [comment]
I needed to install suds-jurko 0.6 to be able to get the last send and receive raw XML
